### ISSUE TITLE
Considering updating jquery version in dependencies?

### ISSUE THREAD

**Issue by tsaiid** [makesites/jquery-contenteditable#8]
I noticed that in the example.html, this plugin runs on jquery v1.7.2. And in the `component.json`, jquery is set to be "~2.0.3". The latest version of jquery is 2.1.4 currently. Do you consider update it or set it to ">=1.7.2" ?

**Comment by tracend** [comment]
Hi @tsaiid,

That's a good recommendation; I believe the plugin supports all versions (in between) as it doesn't rely on obscure features. 

Feel free to send a PR.
